name: Colony 8
favicon: null
layout_spectrum: 0.999
typography_spectrum: 0.4934604975860566
title: Colony 8 - Sci Fi Web Series
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#050014'
    - '#291d29'
    - '#575362'
    - '#a096a1'
    - '#ccc8d9'
  brandStrength: 0.13507455750368536
  lightness: 0.28633162728510797
  saturation: 0.16726191085763276
  rhythmicContrast: 0.2680949568748474
purpose: []
